import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {useAuth} from './lib/auth.jsx';
import {supabase} from './lib/supabase.js';
import {deleteExpense,insertExpense,updateExpense,listUserData,subscribeToChanges} from './lib/data.js';
import Login from './components/Login.jsx';
import ExpenseModal from './components/ExpenseModal.jsx';
import NetWorth from './components/NetWorth.jsx';
import {Budgets,Setup,Planning,Reports} from './components/Management.jsx';

const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const monthKey=v=>String(v||'').slice(0,7);
const currentMonth=()=>new Date().toISOString().slice(0,7);
const monthLabel=m=>new Date(`${m}-01T00:00:00`).toLocaleDateString('en-IN',{month:'long',year:'numeric'});
const esc=v=>String(v??'');
const starterCategories=['Bike petrol','Car petrol','Non Veg','Outing','Groceries','Home Decor','Medicine','Milk','Saloon','Snacks','Veggies'];
const starterPayments=['AXIS Indian Oil CC','AXIS Select CC','BOB UNI Card Rupay CC','Cash','HDFC Dinners Club CC','HDFC Regalia CC','ICICI Amazon Pay CC','ICICI Rupay CC','IDFC First CC','PhonePe','SBI CC','Uni Card CC','Gpay','Pluxee Sodexo'];

function DailyChart({expenses,month}){
 const days=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate();
 const map=useMemo(()=>expenses.filter(x=>monthKey(x.date)===month).reduce((o,x)=>(o[x.date]=(o[x.date]||0)+Number(x.amount||0),o),{}),[expenses,month]);
 const values=Array.from({length:days},(_,i)=>{const d=`${month}-${String(i+1).padStart(2,'0')}`;return{date:d,day:String(i+1).padStart(2,'0'),value:map[d]||0}});
 const max=Math.max(...values.map(x=>x.value),0),today=new Date().toISOString().slice(0,10);
 return <div className="chart" aria-label={`Daily spending for ${monthLabel(month)}`}>{values.map(x=>{const h=max?Math.max(x.value?4:0,x.value/max*100):0;return <div key={x.date} className={`barCol ${x.date===today?'isToday':''}`} title={`${x.date} • ${money(x.value)}`}><div className="bar" style={{height:`${h}%`}}/>{x.value>0&&<em className="barValue">{money(x.value)}</em>}<span>{x.day}</span></div>})}</div>;
}
function Stat({label,value,sub}){return <div className="card stat"><div className="label">{label}</div><div className="num">{value}</div><div className="sub">{sub}</div></div>}
function Modal({open,title,children,onClose,wide=false}){if(!open)return null;return <div className="modal show" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={`modalBox ${wide?'wideModal':''}`}><div className="modalHead"><h2>{title}</h2><button className="close" onClick={onClose}>×</button></div>{children}</div></div>}
function CsvTools({expenses,onImported}){
 const input=React.useRef(null);
 const exportCSV=()=>{const q=v=>`"${String(v??'').replace(/\r?\n/g,' ').replace(/"/g,'""')}"`;const rows=[['Date','Expense Detail','Type of Expense','Amount','Paid via','Paid by','Notes'],...expenses.map(x=>[x.date,x.detail,x.type,x.amount,x.paid_via||x.paidvia,x.paid_by||x.paidby,x.notes])];const csv='\uFEFF'+rows.map(r=>r.map(q).join(',')).join('\r\n')+'\r\n';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='Pulse_Expenses.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 const importCSV=file=>{if(!file)return;const reader=new FileReader();reader.onload=async e=>{const lines=e.target.result.split(/\r?\n/).filter(Boolean);const parse=line=>{const out=[];let c='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'){c+='"';i++;}else if(ch==='"')q=!q;else if(ch===','&&!q){out.push(c);c=''}else c+=ch}out.push(c);return out};const rows=lines.slice(1).map(parse);const data=rows.map(r=>({date:r[0]?.trim(),detail:r[1]?.trim(),type:r[2]?.trim(),amount:Number(r[3]),paid_via:r[4]?.trim(),paid_by:r[5]?.trim(),notes:r[6]?.trim()||''})).filter(x=>x.date&&x.detail&&Number.isFinite(x.amount));if(!data.length)return alert('No valid rows found.');if(!confirm(`Import ${data.length} expenses?`))return;try{for(const kind of [['categories','type'],['payments','paid_via'],['payers','paid_by']]){const [key,field]=kind;const table=key==='categories'?'categories':key==='payments'?'payment_methods':'payers';const existing=key==='categories'?await supabase.from(table).select('name').eq('user_id',(await supabase.auth.getUser()).data.user.id):await supabase.from(table).select('name').eq('user_id',(await supabase.auth.getUser()).data.user.id);const names=new Set((existing.data||[]).map(x=>x.name));const missing=[...new Set(data.map(x=>x[field]).filter(Boolean))].filter(n=>!names.has(n));if(missing.length){const uid=(await supabase.auth.getUser()).data.user.id;const payload=missing.map(name=>key==='categories'?{user_id:uid,name,icon:'•'}:{user_id:uid,name});const r=await supabase.from(table).insert(payload);if(r.error)throw r.error}}const uid=(await supabase.auth.getUser()).data.user.id;const r=await supabase.from('expenses').insert(data.map(x=>({...x,user_id:uid})));if(r.error)throw r.error;await onImported()}catch(err){alert(err.message)}};reader.readAsText(file)};
 return <><input ref={input} type="file" accept=".csv" hidden onChange={e=>importCSV(e.target.files?.[0])}/><button className="btn desktop" onClick={()=>input.current?.click()}>Import CSV</button><button className="btn desktop" onClick={exportCSV}>Export</button></>;
}

function Templates({open,onClose,data,userId,onReload}){
 const [kind,setKind]=useState('categories'),[name,setName]=useState('');
 const cfg={categories:['categories','category'],payments:['payment_methods','payment method'],payers:['payers','Paid by option']};const list=data[kind]||[];
 const add=async()=>{const n=name.trim();if(!n)return;const table=cfg[kind][0];const r=await supabase.from(table).insert(kind==='categories'?{user_id:userId,name:n,icon:'•'}:{user_id:userId,name:n});if(r.error)return alert(r.error.message);setName('');onReload()};
 const del=async id=>{if(!confirm('Remove this option? Existing expenses are not changed.'))return;const r=await supabase.from(cfg[kind][0]).delete().eq('id',id).eq('user_id',userId);if(r.error)return alert(r.error.message);onReload()};
 const reset=async()=>{if(kind==='payers'||!confirm(`Replace your current ${kind} with the Pulse starter list? Existing expenses will not be deleted.`))return;const names=kind==='categories'?starterCategories:starterPayments;const table=cfg[kind][0];let r=await supabase.from(table).delete().eq('user_id',userId);if(r.error)return alert(r.error.message);r=await supabase.from(table).insert(names.map(n=>kind==='categories'?{user_id:userId,name:n,icon:'•'}:{user_id:userId,name:n}));if(r.error)return alert(r.error.message);onReload()};
 return <Modal open={open} title="Template Studio" onClose={onClose} wide><div className="navTabs">{Object.keys(cfg).map(k=><button key={k} className={`tab ${kind===k?'active':''}`} onClick={()=>setKind(k)}>{k==='categories'?'Categories':k==='payments'?'Payment methods':'Paid by'}</button>)}</div><div className="note">These options are private to this Pulse account and protected by Row Level Security.</div><div className="list">{list.map(x=><div className="listRow" key={x.id}><b>{x.name}</b><button className="rowbtn del" onClick={()=>del(x.id)}>Delete</button></div>)}{!list.length&&<div className="empty">No options configured yet.</div>}</div><div className="addRow"><input value={name} onChange={e=>setName(e.target.value)} placeholder={`Add ${cfg[kind][1]}`}/><button className="btn primary" onClick={add}>＋ Add</button></div>{kind!=='payers'&&<div className="templateResetBar"><small>Replace with the Pulse starter list.</small><button className="btn" onClick={reset}>↻ Replace list</button></div>}</Modal>;
}

function AccountModals({data,userId,onReload,session,settings,setSettings,profile,setProfile}){
 const [profileOpen,setProfileOpen]=useState(false),[securityOpen,setSecurityOpen]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[name,setName]=useState(''),[currency,setCurrency]=useState('INR'),[timezone,setTimezone]=useState('Asia/Kolkata'),[confirmText,setConfirmText]=useState(''),[password,setPassword]=useState('');
 const openProfile=async()=>{const r=await supabase.from('profiles').select('*').eq('id',userId).maybeSingle();if(r.error)return alert(r.error.message);const p=r.data||{};setProfile(p);setName(p.display_name||session.user.email.split('@')[0]);setCurrency(p.currency||'INR');setTimezone(p.timezone||'Asia/Kolkata');setProfileOpen(true)};
 const saveProfile=async()=>{if(!name.trim())return alert('Enter a display name.');let r=await supabase.from('profiles').upsert({id:userId,display_name:name.trim(),currency,timezone},{onConflict:'id'}).select().single();if(r.error&&/timezone|column/i.test(r.error.message))r=await supabase.from('profiles').upsert({id:userId,display_name:name.trim(),currency},{onConflict:'id'}).select().single();if(r.error)return alert(r.error.message);setProfile(r.data);setProfileOpen(false);await onReload()};
 const deleteAccount=async()=>{if(confirmText!=='DELETE')return alert('Type DELETE exactly to continue.');if(!password)return alert('Enter your current password.');const reauth=await supabase.auth.signInWithPassword({email:session.user.email,password});if(reauth.error)return alert('Password verification failed. Nothing was deleted.');const r=await supabase.functions.invoke('delete-account',{body:{}});if(r.error)return alert(r.error.message);await supabase.auth.signOut();location.reload()};
 return <><Modal open={settings} title="Settings" onClose={()=>setSettings(false)}><div className="note">Pulse uses a publishable Supabase key in the browser. Never place a service-role key here.</div><div className="list"><button className="btn" onClick={()=>{setSettings(false);openProfile()}}>👤 Profile</button><button className="btn" onClick={()=>{setSettings(false);setSecurityOpen(true)}}>🔐 Security</button><button className="btn danger" onClick={()=>supabase.auth.signOut()}>🚪 Sign out</button><button className="btn danger" onClick={()=>{setSettings(false);setDeleteOpen(true)}}>🗑 Delete my account</button></div></Modal>
 <Modal open={profileOpen} title="Your profile" onClose={()=>setProfileOpen(false)}><p className="modalSubtitle">Update the information shown across Pulse.</p><div className="profileSummary"><div className="profileAvatar">{(name[0]||'P').toUpperCase()}</div><div><strong>{name||'Account'}</strong><small>{session.user.email}</small></div></div><div className="form profileForm"><div className="field full"><label>Display name</label><input value={name} onChange={e=>setName(e.target.value)} maxLength={40}/></div><div className="field"><label>Currency</label><select value={currency} onChange={e=>setCurrency(e.target.value)}><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option><option>SGD</option><option>AED</option></select></div><div className="field"><label>Timezone</label><select value={timezone} onChange={e=>setTimezone(e.target.value)}><option value="Asia/Kolkata">Asia/Kolkata</option><option value="Asia/Singapore">Asia/Singapore</option><option value="Asia/Dubai">Asia/Dubai</option><option value="Europe/London">Europe/London</option><option value="America/New_York">America/New_York</option></select></div><div className="field full"><label>Email</label><input value={session.user.email} readOnly/></div></div><div className="modalFoot"><button className="btn" onClick={()=>setProfileOpen(false)}>Cancel</button><button className="btn primary" onClick={saveProfile}>Save changes</button></div></Modal>
 <Modal open={securityOpen} title="Security" onClose={()=>setSecurityOpen(false)}><div className="note">Pulse uses Supabase Auth and PostgreSQL Row Level Security. Your browser never needs a service-role key.</div><div className="list"><div className="listRow"><div><b>Account</b><small>{session.user.email}</small></div><span className="badge">Authenticated</span></div><div className="listRow"><div><b>Database isolation</b><small>Rows are restricted by your authenticated user ID.</small></div><span className="badge">RLS</span></div></div><div className="dangerPanel"><b>Danger zone</b><small>Delete your Pulse account and all cloud data belonging to it.</small><button className="btn danger" onClick={()=>{setSecurityOpen(false);setDeleteOpen(true)}}>Delete account permanently</button></div></Modal>
 <Modal open={deleteOpen} title="Delete your Pulse account?" onClose={()=>setDeleteOpen(false)}><p className="modalSubtitle">This permanently deletes your Pulse data. This cannot be undone.</p><div className="dangerPanel"><b>Everything in this account will be deleted</b><small>Expenses, categories, payment methods, Paid by options, budgets, recurring plans, goals, reminders and profile data.</small></div><div className="form"><div className="field full"><label>Confirm by typing DELETE</label><input value={confirmText} onChange={e=>setConfirmText(e.target.value.toUpperCase())}/></div><div className="field full"><label>Current password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></div></div><div className="modalFoot"><button className="btn" onClick={()=>setDeleteOpen(false)}>Cancel</button><button className="btn danger" onClick={deleteAccount}>Delete permanently</button></div></Modal></>;
}

function Home({data,month,setMonth,cat,setCat,pay,setPay,search,setSearch,onReset,onAdd,onEdit,onDelete,setView}){
 const filtered=useMemo(()=>data.expenses.filter(x=>monthKey(x.date)===month&&(cat==='All'||x.type===cat)&&(pay==='All'||(x.paid_via||x.paidvia)===pay)&&(!search||[x.detail,x.type,x.paid_via,x.paidvia,x.paid_by,x.paidby,x.notes].join(' ').toLowerCase().includes(search.toLowerCase()))),[data.expenses,month,cat,pay,search]);
 const total=filtered.reduce((s,x)=>s+Number(x.amount||0),0),cats=Object.entries(filtered.reduce((o,x)=>(o[x.type]=(o[x.type]||0)+Number(x.amount||0),o),{})).sort((a,b)=>b[1]-a[1]),largest=Math.max(0,...filtered.map(x=>Number(x.amount||0)));
 const overall=data.budgets.find(b=>monthKey(b.month)===month&&!b.category_id),spent=data.expenses.filter(x=>monthKey(x.date)===month).reduce((s,x)=>s+Number(x.amount||0),0),pct=overall?Math.min(100,spent/Math.max(Number(overall.amount),1)*100):0;
 const prev=useMemo(()=>{const d=new Date(`${month}-01T00:00:00`);d.setMonth(d.getMonth()-1);return d.toISOString().slice(0,7)},[month]);const prevTotal=data.expenses.filter(x=>monthKey(x.date)===prev).reduce((s,x)=>s+Number(x.amount||0),0);const change=prevTotal?((spent-prevTotal)/prevTotal*100):null;
 const months=[...new Set(data.expenses.map(x=>monthKey(x.date)).filter(Boolean))].sort().reverse();
 return <section data-view="home"><div className="hero"><div className="heroGrid"><div><div className="eyebrow">PULSE OVERVIEW</div><h2><span className="greetingHello">Good {new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'} 👋</span><span className="greetingName">{data.profile?.display_name||'there'}</span></h2><p>Track today. Understand this month. Stay in control.</p><div className="quick"><button onClick={onAdd}>＋ Quick expense</button><button onClick={()=>setSearch('Bike petrol')}>• Bike petrol</button><button onClick={()=>setSearch('Car petrol')}>• Car petrol</button><button onClick={()=>setSearch('EB Bill')}>• EB Bill</button></div></div><div><div className="label">This month</div><div className="heroTotal">{money(total)}</div><div className="delta">{filtered.length} transaction{filtered.length===1?'':'s'} in selected view</div></div></div><div className="filters"><select className="control" value={month} onChange={e=>setMonth(e.target.value)}>{months.map(m=><option key={m} value={m}>{monthLabel(m)}</option>)}</select><select className="control" value={cat} onChange={e=>setCat(e.target.value)}><option value="All">All categories</option>{data.categories.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select><select className="control" value={pay} onChange={e=>setPay(e.target.value)}><option value="All">All payment methods</option>{data.payments.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select><input className="control" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search expenses..."/><button className="btn" onClick={onReset}>Reset</button></div></div>
 <div className="stats"><Stat label="Transactions" value={filtered.length} sub="selected view"/><Stat label="Average" value={money(filtered.length?total/filtered.length:0)} sub="per transaction"/><Stat label="Largest" value={money(largest)} sub="single expense"/><Stat label="Top category" value={cats[0]?.[0]||'—'} sub={money(cats[0]?.[1]||0)}/></div>
 <div className="grid2"><section className="card cardPad"><h3>Spending pulse</h3><DailyChart expenses={filtered} month={month}/></section><section className="card cardPad"><h3>Category breakdown</h3>{cats.length?<div className="cats">{cats.slice(0,7).map(([n,v])=><div className="cat" key={n}><div>{n}<div className="line"><div className="fill" style={{width:`${v/(cats[0]?.[1]||1)*100}%`}}/></div></div><b>{money(v)}</b></div>)}</div>:<div className="empty">No categories in this view.</div>}</section></div>
 <div className="grid2" style={{marginTop:15}}><section className="card cardPad"><h3>Budget health</h3>{overall?<><div className="budgetTop"><strong>{money(spent)} spent</strong><strong>{money(overall.amount)}</strong></div><div className="progress"><div style={{width:`${pct}%`}}/></div><p className="sub">{money(Math.max(0,Number(overall.amount)-spent))} remaining • {pct.toFixed(0)}% used</p></>:<div className="empty">No overall budget for {monthLabel(month)}.<br/><button className="btn primary" style={{marginTop:10}} onClick={()=>setView('budgets')}>Set one</button></div>}</section><section className="card cardPad"><h3>Pulse insights</h3><div className="insight"><strong>{change===null?'✨ Build your first baseline':`${change>=0?'📈':'📉'} ${Math.abs(change).toFixed(1)}% ${change>=0?'higher':'lower'} than last month`}</strong><small>{change===null?'Keep logging expenses and Pulse will compare your spending over time.':`${money(spent)} this month vs ${money(prevTotal)} last month.`}</small></div>{cats[0]&&<div className="insight"><strong>🎯 {cats[0][0]} is your top category</strong><small>{money(cats[0][1])} in the selected view.</small></div>}</section></div>
 <Recent rows={filtered} onEdit={onEdit} onDelete={onDelete} onAdd={onAdd}/></section>;
}
function Recent({rows,onEdit,onDelete,onAdd}){const a=[...rows].sort((x,y)=>String(y.date).localeCompare(String(x.date))).slice(0,100);return <section className="card tableCard"><div className="tableHead"><div><h3 style={{margin:0}}>Recent expenses</h3><small className="sub">Showing {a.length} of selected view</small></div><button className="btn primary" onClick={onAdd}>＋ Add expense</button></div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Expense</th><th>Category</th><th>Amount</th><th>Paid via</th><th>Paid by</th><th>Actions</th></tr></thead><tbody>{a.length?a.map(x=><tr key={x.id}><td>{x.date}</td><td><b>{x.detail}</b>{x.notes&&<small>{x.notes}</small>}</td><td><span className="pill">{x.type}</span></td><td className="amount">{money(x.amount)}</td><td>{x.paid_via||x.paidvia||'—'}</td><td>{x.paid_by||x.paidby||'—'}</td><td><button className="rowbtn" onClick={()=>onEdit(x)}>Edit</button><button className="rowbtn del" onClick={()=>onDelete(x.id)}>Delete</button></td></tr>):<tr><td colSpan="7" className="empty">No expenses in this view.<br/><button className="btn primary" style={{marginTop:10}} onClick={onAdd}>＋ Add expense</button></td></tr>}</tbody></table></div></section>}

function Expenses({data,onEdit,onDelete,onAdd}){const [q,setQ]=useState('');const rows=data.expenses.filter(x=>[x.detail,x.type,x.paid_via,x.paid_by,x.notes].join(' ').toLowerCase().includes(q.toLowerCase())).sort((a,b)=>String(b.date).localeCompare(String(a.date)));return <section className="card tableCard"><div className="tableHead"><div><h3>All expenses</h3><small>{rows.length} shown · {data.expenses.length} total</small></div><div className="actions"><input className="control" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search expenses…"/><CsvTools expenses={data.expenses} onImported={data.reload}/></div></div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Expense</th><th>Category</th><th>Amount</th><th>Paid via</th><th>Paid by</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.date}</td><td><b>{x.detail}</b><small>{x.notes||''}</small></td><td><span className="pill">{x.type}</span></td><td className="amount">{money(x.amount)}</td><td>{x.paid_via||x.paidvia||'—'}</td><td>{x.paid_by||x.paidby||'—'}</td><td><button className="rowbtn" onClick={()=>onEdit(x)}>Edit</button><button className="rowbtn del" onClick={()=>onDelete(x.id)}>Delete</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No matching expenses.</div>}</div></section>}

export default function App(){
 const {session,loading}=useAuth();const [data,setData]=useState({expenses:[],categories:[],payments:[],payers:[],budgets:[],goals:[],networth:[],recurring:[],reminders:[],profile:null});const [view,setView]=useState('home'),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[settings,setSettings]=useState(false),[templates,setTemplates]=useState(false);
 const load=useCallback(async()=>{if(!session)return;setBusy(true);try{const next=await listUserData(session.user.id);const p=await supabase.from('profiles').select('*').eq('id',session.user.id).maybeSingle();setData({...next,userId:session.user.id,profile:p.data||null,reload:load})}catch(e){alert(`Pulse could not load cloud data: ${e.message}`)}finally{setBusy(false)}},[session]);
 useEffect(()=>{load()},[load]);useEffect(()=>{if(!session)return subscribeToChanges(session.user.id,load)},[session,load]);
 const [month,setMonth]=useState(currentMonth()),[cat,setCat]=useState('All'),[pay,setPay]=useState('All'),[search,setSearch]=useState('');
 if(loading)return <div className="loading">Loading Pulse…</div>;if(!session)return <Login/>;
 const save=async form=>{try{if(editing)await updateExpense(session.user.id,editing.id,form);else await insertExpense(session.user.id,form);setModal(false);setEditing(null);await load()}catch(e){alert(`Could not save expense: ${e.message}`)}};
 const del=async id=>{if(!confirm('Delete this expense?'))return;try{await deleteExpense(session.user.id,id);await load()}catch(e){alert(`Could not delete expense: ${e.message}`)}};
 const nav=[['home','⌂','Home'],['expenses','▤','Expenses'],['reports','▥','Reports'],['budgets','◫','Budgets'],['wealth','◈','Wealth'],['planning','◎','Planning'],['setup','⚙','Setup']];
 const reset=()=>{setMonth(currentMonth());setCat('All');setPay('All');setSearch('')};
 return <><div className="app"><header className="top"><div className="brand"><div className="logo">✦</div><div><h1>Pulse</h1><p>Your private money command center</p></div></div><div className="actions"><span className="badge">☁ Synced</span><nav className="desktopNav">{nav.map(([id,icon,label])=><button key={id} className={`navLink ${view===id?'active':''}`} onClick={()=>setView(id)}>{label}</button>)}</nav><button className="btn accountBtn" onClick={()=>setSettings(true)}>👤 <span>{data.profile?.display_name||session.user.email.split('@')[0]}</span>⌄</button><button className="btn desktop" onClick={()=>setSettings(true)}>⚙ Settings</button><button className="btn primary" onClick={()=>{setEditing(null);setModal(true)}}>＋ Add expense</button></div></header>
 {view==='home'&&<Home data={data} month={month} setMonth={setMonth} cat={cat} setCat={setCat} pay={pay} setPay={setPay} search={search} setSearch={setSearch} onReset={reset} onAdd={()=>{setEditing(null);setModal(true)}} onEdit={x=>{setEditing(x);setModal(true)}} onDelete={del} setView={setView}/>} 
 {view==='expenses'&&<Expenses data={data} onEdit={x=>{setEditing(x);setModal(true)}} onDelete={del} onAdd={()=>{setEditing(null);setModal(true)}}/>}
 {view==='reports'&&<Reports data={data}/>} {view==='budgets'&&<Budgets data={data} userId={session.user.id} onReload={load}/>} {view==='wealth'&&<NetWorth data={data} userId={session.user.id} onReload={load}/>} {view==='planning'&&<Planning data={data} userId={session.user.id} onReload={load}/>} {view==='setup'&&<Setup data={data} userId={session.user.id} onReload={load}/>} 
 <nav className="bottomNav">{nav.slice(0,5).map(([id,icon,label])=><button className={view===id?'active':''} key={id} onClick={()=>setView(id)}>{icon}<br/>{label}</button>)}</nav></div>
 <ExpenseModal open={modal} initial={editing} onClose={()=>{setModal(false);setEditing(null)}} onSave={save} categories={data.categories} payments={data.payments} payers={data.payers}/>
 <Templates open={templates} onClose={()=>setTemplates(false)} data={data} userId={session.user.id} onReload={load}/>
 <AccountModals data={data} userId={session.user.id} onReload={load} session={session} settings={settings} setSettings={setSettings} profile={data.profile} setProfile={p=>setData(d=>({...d,profile:p}))}/>
 {busy&&<div className="syncing">Syncing…</div>}</>;
}
